name: veris_vectordb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pyyaml>=6.0
  - requests>=2.31.0
  - pip:
    - llama-index>=0.9.0
    - llama-index-llms-bedrock
    - llama-index-embeddings-bedrock
    - llama-index-vector-stores-qdrant
    - qdrant-client>=1.7.0
    - boto3>=1.34.0
    - python-dotenv>=1.0.0
    # for ingestion
    - pymupdf
    # for async
    - llama-index-llms-bedrock-converse
    # for memory
    - mem0ai
    


